name: actionsテスト

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    if: github.event.base_ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ toJson(github) }}'
